services:
  backend:
    env_file:
      - mentally-backend/.env
    build:
      context: ./mentally-backend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8000:8000"  # Use localhost or 127.0.0.1 for binding
    networks:
      - app-network

  frontend:
    env_file:
      - mentally-frontend/.env
    build:
      context: ./mentally-frontend
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - "127.0.0.1:3006:3006"  # Same for frontend if needed
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
