import requests
import json

# Test data for mental health update
test_data = {
    "surprise": 1000,
}

# Example JWT token (replace with an actual JWT)
token="eyJhbGciOiJSUzI1NiIsImtpZCI6IjFhYWMyNzEwOTkwNDljMGRmYzA1OGUwNjEyZjA4ZDA2YzMwYTA0MTUiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vbWVudGFsbHktOTU3ZGIiLCJhdWQiOiJtZW50YWxseS05NTdkYiIsImF1dGhfdGltZSI6MTczNDg1NDIxNCwidXNlcl9pZCI6Ikc4VHJsTktIZjlnRXhvTDFuZnB6a1NnbmZBRDIiLCJzdWIiOiJHOFRybE5LSGY5Z0V4b0wxbmZwemtTZ25mQUQyIiwiaWF0IjoxNzM0ODU0MjE0LCJleHAiOjE3MzQ4NTc4MTQsImVtYWlsIjoibWF4dHJpbmg0QGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwiZmlyZWJhc2UiOnsiaWRlbnRpdGllcyI6eyJlbWFpbCI6WyJtYXh0cmluaDRAZ21haWwuY29tIl19LCJzaWduX2luX3Byb3ZpZGVyIjoicGFzc3dvcmQifX0.4VkPXjav9GazmmVVX_NeK_LafOoowYBspIQbbLTqpCLUePoCsbIlKJd5WbKMZY2FMUlyAremOA0rRlSHzTMd5cBKYrXxhnrq22mDQVoYllPJIcOAqxFty11xDyPd72c4j8Ep_p8sNNdCMvYBttedemgM8RqqY90P1ITnxHzjaAo9jhQ8nUIGcb0Vd-rPfuzUpg7I1vWBYz0eJFATbUfBC-TeBZOLaYibbVMp8DP4XnqTlU4UUVhTahb9nXjj91eJJBYozDOdeZqnggoR9hkvDWYgheTkyNNglK-rmDSbS6EOON875fCArbuZ8hP3nR0zjZ3wLyK785ffnntRDo78Ww"
# Define the API URL
url = "http://localhost:8000/user/update-mental-data"

# Define the headers and include the JWT token
headers = {
    "Authorization": token,
    "Content-Type": "application/json"
}

response = requests.post(url, headers=headers, json=test_data)
print(response.status_code, response.text)


